name: Pulumi up
on:
  pull_request_review:
    type: [submitted]
    branches: [main]

permissions:
  pull-requests: write

jobs:
  preview:
    if: github.event.review.state == 'APPROVED'
    name: Update
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: pulumi/actions@v5
      with:
        command: update
        stack-name: organization/my-infra/dev
        cloud-url: ${{ vars.PULUMI_BACKEND_URL }}
        comment-on-pr: true
      env:
        PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
        CIVO_TOKEN: ${{ secrets.CIVO_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
        AWS_HOST: ${{ vars.AWS_HOST }}

